version: "3.8"

services:
  electron-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    network_mode: host
    command: ["xvfb-run", "npm", "start"]
